import type { Project } from "./types";

export const projects: Project[] = [
  {
    id: "flower-lab",
    name: "花屿生活馆",
    channel: "小红书 + 微信线索",
    category: "本地鲜花",
    status: "已完成导入",
    updatedAt: "今天 10:20",
    metrics: {
      revenue: 48620,
      orders: 164,
      leads: 92,
      engagementRate: 8.7,
      contentCount: 18,
      conversionRate: 12.4,
    },
    trend: [
      { date: "周一", views: 6800, sales: 5200, leads: 9 },
      { date: "周二", views: 7400, sales: 6100, leads: 11 },
      { date: "周三", views: 12200, sales: 9800, leads: 20 },
      { date: "周四", views: 8600, sales: 7300, leads: 13 },
      { date: "周五", views: 10400, sales: 8400, leads: 17 },
      { date: "周六", views: 14200, sales: 7900, leads: 15 },
      { date: "周日", views: 9600, sales: 9900, leads: 7 },
    ],
    content: [
      {
        title: "99 元周末花束怎么选",
        platform: "小红书",
        views: 14200,
        likes: 986,
        saves: 451,
        comments: 83,
        conversionHint: "收藏高，适合做套餐页入口",
      },
      {
        title: "办公室前台花 3 天换新实拍",
        platform: "抖音",
        views: 12200,
        likes: 721,
        saves: 198,
        comments: 54,
        conversionHint: "企业客户询价明显增加",
      },
      {
        title: "毕业季花束避坑清单",
        platform: "小红书",
        views: 8600,
        likes: 604,
        saves: 336,
        comments: 61,
        conversionHint: "评论区问题集中在配送",
      },
    ],
    products: [
      { name: "周末混搭花束", revenue: 16800, orders: 56, conversion: 15.2 },
      { name: "企业前台周花", revenue: 12400, orders: 18, conversion: 9.8 },
      { name: "毕业季向日葵花束", revenue: 9200, orders: 42, conversion: 11.4 },
    ],
    leads: [
      {
        name: "李女士",
        source: "小红书私信",
        intent: "生日花束，预算 300",
        lastAction: "已询问配送时间",
        priority: "高",
      },
      {
        name: "城东咖啡店",
        source: "微信表单",
        intent: "长期桌花合作",
        lastAction: "留下门店地址",
        priority: "高",
      },
      {
        name: "陈先生",
        source: "抖音评论",
        intent: "毕业花束",
        lastAction: "询价未回复",
        priority: "中",
      },
    ],
    diagnosis: [
      {
        title: "内容表现",
        finding: "价格明确的选购型内容最容易带来收藏和私信。",
        evidence: "Top 内容中“99 元周末花束怎么选”收藏 451 次，高于其他内容 36%。",
        action: "下周继续做 3 条价格带内容：99 元、199 元、企业周花套餐。",
      },
      {
        title: "产品转化",
        finding: "周末混搭花束销售效率最高，但企业周花客单价更高。",
        evidence: "周末花束贡献 56 单，企业周花仅 18 单但销售额达 12400 元。",
        action: "把企业周花放入私信自动回复和门店报价单第一屏。",
      },
      {
        title: "下周选题",
        finding: "用户正在问配送、预算和场景搭配。",
        evidence: "高互动内容评论集中在配送时间、毕业季预算、办公室场景。",
        action: "发布“同城送花时间表”和“毕业季不同预算搭配”两类内容。",
      },
      {
        title: "客户跟进优先级",
        finding: "企业合作和已明确预算的线索应优先处理。",
        evidence: "高优先级线索均已留下预算、地址或长期合作意向。",
        action: "今天先跟进李女士和城东咖啡店，给出具体套餐和可配送时间。",
      },
    ],
    report: {
      result: [
        "本周销售额 48620 元，订单 164 单。",
        "新增线索 92 条，其中高意向线索 2 条需要当天跟进。",
        "内容互动率 8.7%，选购型内容表现最好。",
      ],
      problems: [
        "高曝光内容没有统一承接到套餐页，浪费了一部分收藏用户。",
        "配送相关问题反复出现，说明下单前顾虑还没有被解决。",
      ],
      opportunities: [
        "企业周花客单价高，可以作为下周重点转化产品。",
        "毕业季即将到来，预算型选题可以继续放大。",
      ],
      nextActions: [
        "制作 3 个价格带套餐图，放到私信回复和置顶笔记。",
        "发布同城配送时间说明，减少重复咨询。",
        "优先跟进 2 条高意向线索，并记录是否成交。",
      ],
    },
  },
  {
    id: "tea-studio",
    name: "山野茶事",
    channel: "抖音 + 有赞订单",
    category: "茶叶零售",
    status: "建议复盘",
    updatedAt: "昨天 18:45",
    metrics: {
      revenue: 73280,
      orders: 238,
      leads: 51,
      engagementRate: 5.9,
      contentCount: 12,
      conversionRate: 8.1,
    },
    trend: [
      { date: "周一", views: 9200, sales: 8200, leads: 5 },
      { date: "周二", views: 8800, sales: 7600, leads: 4 },
      { date: "周三", views: 13400, sales: 12900, leads: 8 },
      { date: "周四", views: 10100, sales: 9300, leads: 6 },
      { date: "周五", views: 11200, sales: 10800, leads: 7 },
      { date: "周六", views: 18600, sales: 16400, leads: 13 },
      { date: "周日", views: 7900, sales: 12100, leads: 8 },
    ],
    content: [
      {
        title: "新手怎么喝懂白茶",
        platform: "抖音",
        views: 18600,
        likes: 1102,
        saves: 306,
        comments: 94,
        conversionHint: "适合承接入门套装",
      },
      {
        title: "春茶和秋茶有什么区别",
        platform: "抖音",
        views: 13400,
        likes: 812,
        saves: 244,
        comments: 62,
        conversionHint: "评论区教育需求明显",
      },
      {
        title: "办公室泡茶 3 件套",
        platform: "小红书",
        views: 10100,
        likes: 493,
        saves: 221,
        comments: 39,
        conversionHint: "适合做组合装",
      },
    ],
    products: [
      { name: "白茶入门 3 罐装", revenue: 28400, orders: 96, conversion: 10.6 },
      { name: "办公室冷泡组合", revenue: 19600, orders: 74, conversion: 8.7 },
      { name: "老客户复购礼盒", revenue: 14800, orders: 31, conversion: 6.9 },
    ],
    leads: [
      {
        name: "王女士",
        source: "抖音私信",
        intent: "送礼，预算 500",
        lastAction: "询问包装",
        priority: "高",
      },
      {
        name: "赵先生",
        source: "有赞咨询",
        intent: "办公室冷泡",
        lastAction: "加购未付款",
        priority: "中",
      },
      {
        name: "周女士",
        source: "评论区",
        intent: "新手入门",
        lastAction: "问口味区别",
        priority: "中",
      },
    ],
    diagnosis: [
      {
        title: "内容表现",
        finding: "知识科普内容带来最高浏览，但需要更直接的商品承接。",
        evidence: "“新手怎么喝懂白茶”浏览 18600，明显高于本周均值。",
        action: "每条科普内容结尾固定推荐一个入门套装。",
      },
      {
        title: "产品转化",
        finding: "入门 3 罐装是当前主力转化产品。",
        evidence: "该商品贡献 28400 元销售额和 96 单。",
        action: "把入门装作为直播间和短视频评论区的默认推荐。",
      },
      {
        title: "下周选题",
        finding: "新手问题和办公场景值得继续做。",
        evidence: "Top 内容集中在白茶入门、茶叶区别、办公室泡茶。",
        action: "做 2 条新手避坑和 1 条办公室茶水间方案。",
      },
      {
        title: "客户跟进优先级",
        finding: "送礼预算明确的线索最接近成交。",
        evidence: "王女士已明确预算 500，并询问包装细节。",
        action: "优先发送礼盒图和顺丰发货时间。",
      },
    ],
    report: {
      result: [
        "本周销售额 73280 元，订单 238 单。",
        "入门白茶套装贡献最高，适合作为新客入口。",
        "内容浏览峰值来自新手科普类视频。",
      ],
      problems: [
        "科普内容和商品链接之间的承接还不够明确。",
        "部分加购用户没有被及时二次提醒。",
      ],
      opportunities: [
        "送礼场景有明确预算，适合推出 399/599 两档礼盒。",
        "办公室冷泡组合适合做批量采购线索。",
      ],
      nextActions: [
        "给 Top 3 视频补充固定商品承接话术。",
        "筛选加购未付款用户，发送一次限时提醒。",
        "制作送礼预算表，作为私信回复素材。",
      ],
    },
  },
  {
    id: "snack-shop",
    name: "阿宁零食铺",
    channel: "拼多多 + 微信线索",
    category: "休闲食品",
    status: "等待导入",
    updatedAt: "3 天前",
    metrics: {
      revenue: 21940,
      orders: 312,
      leads: 28,
      engagementRate: 4.2,
      contentCount: 8,
      conversionRate: 5.6,
    },
    trend: [
      { date: "周一", views: 3900, sales: 2600, leads: 3 },
      { date: "周二", views: 4200, sales: 3100, leads: 4 },
      { date: "周三", views: 5100, sales: 3300, leads: 5 },
      { date: "周四", views: 4600, sales: 2900, leads: 3 },
      { date: "周五", views: 5800, sales: 3600, leads: 6 },
      { date: "周六", views: 6200, sales: 3400, leads: 4 },
      { date: "周日", views: 4100, sales: 3040, leads: 3 },
    ],
    content: [
      {
        title: "办公室下午茶零食箱",
        platform: "小红书",
        views: 6200,
        likes: 241,
        saves: 119,
        comments: 24,
        conversionHint: "适合做组合装",
      },
      {
        title: "低卡零食真实测评",
        platform: "抖音",
        views: 5800,
        likes: 198,
        saves: 86,
        comments: 18,
        conversionHint: "评论区关注热量",
      },
      {
        title: "宿舍囤货清单",
        platform: "小红书",
        views: 5100,
        likes: 176,
        saves: 92,
        comments: 21,
        conversionHint: "学生场景明显",
      },
    ],
    products: [
      { name: "办公室零食箱", revenue: 7600, orders: 68, conversion: 7.2 },
      { name: "低卡魔芋组合", revenue: 5300, orders: 91, conversion: 5.8 },
      { name: "宿舍囤货 20 包", revenue: 4200, orders: 76, conversion: 4.9 },
    ],
    leads: [
      {
        name: "林女士",
        source: "微信表单",
        intent: "公司团购",
        lastAction: "询问满减",
        priority: "高",
      },
      {
        name: "小陈",
        source: "小红书私信",
        intent: "宿舍囤货",
        lastAction: "问口味",
        priority: "中",
      },
      {
        name: "刘先生",
        source: "拼多多咨询",
        intent: "低卡零食",
        lastAction: "仅浏览",
        priority: "低",
      },
    ],
    diagnosis: [
      {
        title: "内容表现",
        finding: "场景化组合比单品测评更容易被保存。",
        evidence: "办公室零食箱保存 119 次，是本周最高。",
        action: "继续做办公室、宿舍、追剧三类场景清单。",
      },
      {
        title: "产品转化",
        finding: "组合装比单品更适合承接内容流量。",
        evidence: "办公室零食箱销售额 7600 元，排名第一。",
        action: "上传新一轮订单数据后，重点观察组合装复购。",
      },
      {
        title: "下周选题",
        finding: "低卡和办公室团购是两个可放大的方向。",
        evidence: "高互动内容和高优先级线索均指向这两个场景。",
        action: "做“办公室零食预算表”和“低卡零食红黑榜”。",
      },
      {
        title: "客户跟进优先级",
        finding: "团购线索优先级最高。",
        evidence: "林女士已经询问满减，具备批量购买可能。",
        action: "优先发送团购阶梯价和可选口味表。",
      },
    ],
    report: {
      result: [
        "本周销售额 21940 元，订单 312 单。",
        "办公室零食箱是当前销售额最高的组合商品。",
        "内容互动偏低，需要继续优化标题和封面。",
      ],
      problems: [
        "低卡内容有浏览但转化一般，商品卖点还不够清楚。",
        "最近 3 天未导入新数据，看板可能滞后。",
      ],
      opportunities: [
        "办公室团购线索值得优先跟进。",
        "宿舍和追剧场景可以形成低价组合包。",
      ],
      nextActions: [
        "补充最新订单和线索表。",
        "给办公室团购做一张阶梯报价图。",
        "把低卡组合卖点改成热量、饱腹感和口味三个维度。",
      ],
    },
  },
];

export function getProject(projectId: string) {
  return projects.find((project) => project.id === projectId) ?? projects[0];
}
